### ISSUE TITLE
Automatically work out if S21

### ISSUE THREAD

**Issue by revk** [revk/ESP32-Daikin#10]
Try initial comms as S21 or not and work it out, rather than a config.

**Comment by antonsb** [comment]
Does this means that S21 socket interconnection may be supported as well?
Currently my BRP069C4X has very small connector that i have problem to find online as well as connect pins to it without cutting the wire - thus voiding warranty on the unit. But there is a free S21 slot

**Comment by revk** [comment]
There is an MQTT based setting for S21 mode, but I really should make it auto detect some time. Both types of unit I have had a WiFi connect lead and the Daikin WiFi so was easy.

**Comment by antonsb** [comment]
lead goes to mine as well, but it's small JST SHJ 1mm pitch type connector (on both sides).On PCB it does not connect to S21,but to some other port module looks like this:
![index](https://user-images.githubusercontent.com/31347821/211902228-76ed756b-1325-4b79-bbad-ad394f55c436.jpg)

**Comment by antonsb** [comment]
If it worked from S21,it would be much easier (at least for my case) to make custom wire harness, then to hunt down that small connector.

**Comment by revk** [comment]
I can look in to making it auto detect soon. But I can probably sort a make menuconfig for S21 in the mean time. Probably in the morning.

**Comment by antonsb** [comment]
Damn that's fast. I just ordered JST EH for S21 from Ali, not sure when they will arrive and i will be able to test this.

**Comment by revk** [comment]
Well I hope it works. I'll let you know when I have tested.

**Comment by revk** [comment]
I have added the S21 setting to make menuconfig now. Like the other settings this is just the default and can be overridden using MQTT, but it should allow you to build an S21 based build to try.

**Comment by antonsb** [comment]
build seems to be working for me with S21 option, i would check functionality next week as i will get some connectors for cabling

**Comment by revk** [comment]
Ok not working very well...

**Comment by revk** [comment]
It seems to be working well now, and clean from power up as well.

Only concern is the non S21 model could, with a lot of poking crap at it, get in to a state of just reporting errors. This may mean we need a null header or some such. Something to consider if the problem is seen in the wild.
