### ISSUE TITLE
ESP32 wroom ignores menucofig wireless settings

### ISSUE THREAD

**Issue by antonsb** [revk/ESP32-Daikin#12]
I'm not that familiar with ESP chipsets, but it seems that wireless settings are not updated from menuconfig. On first build they are saved into some ESP32 memory that is not erased after reflash and ESP tries to connect on AP that was saved previously.  I even tried writing different bin files and new git clones.

**Comment by revk** [comment]
The menuconfig settings are the initial/default. If you have set them then yes it will connect to the saved previously settings, obviously. If it cannot connect it should got to AP mode and allow new settings via a web interface.

**Comment by revk** [comment]
You can idf.py erase-flash to clear them.

**Comment by revk** [comment]
The menu config even makes it clear:
                This defines the factory reset default WiFi SSID
                This defines the factory reset default WiFi passphrase

**Comment by antonsb** [comment]
sorry missed that part.
Thanks for clarification.
