### ISSUE TITLE
[FEATURE] Min/Max Temperatur in Faikin auto mode

### ISSUE THREAD

**Issue by ckvsoft** [revk/ESP32-Daikin#156]
It would be nice if there was the option to enter the minimum temperature for heating or the maximum temperature for cooling. Also controllable with mqtt.

Description.
Suppose I set the heating temperature in Faikin auto mode to 23 degrees
The Daikin system is then regulated between 16 and 32 degrees. But it shouldn't actually do that. It gets cold on its own during the heating season. Although there is no switch to cooling, the fluid temperature still gets down and the fan blows the air that is too cold. Is particularly bad when there is a night-time depression. Then an attempt is made to get the temperature to the newly set temperature. That is not necessary. Just make sure the temperature doesn't fall below that

The opposite is the case with cooling. When the temperature falls below the desired value, heating occurs. Not necessary in summer either.

Since Faikin does this temperature control in auto mode, it should be possible.

Faikin-S1-PICO: 4dfbddd 2023-11-18T12:22:21

**Comment by revk** [comment]
I think mine does indeed have a different range for heating and cooling. So sounds sensible. I'll look in the morning.

**Comment by ckvsoft** [comment]
I have activated locked. That already works.
Only when heating is the temperature control set by the Daikin to 16 degrees "Heating", the fluid temperature goes down and the fan blows. This is a waste of energy. At least the fan should stop blowing

This always happens when my night setback is activated.
e.g. It is 23 degrees and you set the temperature down to 19 degrees then the Daikin switches to 16 degrees and tries to reach 19 degrees. This means that the goal is achieved much earlier than necessary.
Am I alone with this problem?

**Comment by revk** [comment]
I am still confused - what alternative is there than heat to a lower temp. If it does not cut fan in that what would be better to tell it?

**Comment by ckvsoft** [comment]
If I set tmin and tmax with an mqtt message it works, but that's a fixed setting and Faikin reboots every time - I would need something like this as a command that takes over the weret but doesn't save it. I can then implement the control in an external thermostat

**Comment by ckvsoft** [comment]
> I am still confused - what alternative is there than heat to a lower temp. If it does not cut fan in that what would be better to tell it?

I just don't understand why the temperature of the Daikin is set below the target temperature of Faikin when heating

**Comment by ckvsoft** [comment]
> I am still confused - what alternative is there than heat to a lower temp. If it does not cut fan in that what would be better to tell it?

Sorry, my native language is not English and I probably can't get this across correctly. But I'll give it a try.

E.g. The heating is set to 25 degrees then it should be heated up with tmax. The closer I get to this temperature, the Daikin temperature can be regulated down. But never below the target temperature.

Now it looks like the setting is temporarily reduced to tmin. Even in heating mode.

Of course, when it comes to cooling, it should work the other way around.

I may see a problem if the target temperature is manually changed downwards. But it should still not be forced down to this temperature. As I said, when heating, it gets colder even without the climate being forced, and vice versa when cooling

**Comment by revk** [comment]
Thanks, but still not sure of the issue. "Heating to tmin" does not make it go colder than target. It simple stops heating. Heating to anything much lower than the target stops it heating. I set a lot lower as I don't trust it to be getting temp accurately when using an external reference.

There is a setting that controls how much lower than target it goes to "turn off heating" and how much higher that target it sets to "turn off cooling". You can change these. If you set to zero it will do what you want I expect. They should be in the manual. There are 4 settings to control temp adjustments for this.

**Comment by ckvsoft** [comment]
I'll check that out.

It's not clear to me why it has now gone to 10 degrees (my current tmin).

It's expected to heat up to 25.5 degrees, but it's only 20,2 degrees and it doesn't heat any further.
![grafik](https://github.com/revk/ESP32-Faikin/assets/16374447/fd01c7e8-a6bd-4deb-82ec-32f026529f92)

**Comment by ckvsoft** [comment]
I have deactivated the Daikin auto mode. The controls don't work as I thought they would. I just have to make do with the Daikin control. At least the set temperature is reached. No idea what's going on.
The liquid temperature keeps going down to minus 14 degrees even though the target temperature is still far from being reached. Unfortunately not useful for me. Too bad

**Comment by revk** [comment]
Sorry to hear that. There are a lot of settings you can try to make it do what you want.

**Comment by ckvsoft** [comment]
Unfortunately I can't get any results. If anything, it's getting worse and worse. Liquid already reached -29 degrees. It always turns off with one star, even if Faikin is actually set to disabled and Faikin ato is set to off.
The only thing used is env with target.
Is there a way to reset to default values?

**Comment by revk** [comment]
Err, not easily. Try setting/Faikin to get the current full set of settings and see what is wrong?
