### ISSUE TITLE
[BUG] System appears offline always since af4d48f patch

### ISSUE THREAD

**Issue by jamofer** [revk/ESP32-Daikin#159]
**Faikin hardware**
Faikin hardware purchased in Amazon on 1 Jun 2023: Faikin-S1-PICO

**Daikin hardware**
Model: ADEA71A2VEB
Protocol: X50 

**Describe the bug**
Since af4d48f 2023-12-01T16:34:47 upgrade system appears offline always. (I tried to reboot, to power off/on the AC plug...)

**To Reproduce**
1. Power on the AC
2. Faikin web shows "System is off line."

**Expected behavior**
Normal startup behavior

**Comment by jamofer** [comment]
Here is it a screenshot of the current status
![imagen](https://github.com/revk/ESP32-Faikin/assets/9080627/029bb97f-d863-4d1d-81ca-39f04d5a0be8)

**Comment by jamofer** [comment]
Wow... five minutes ago it showed X50. I already tried to power cycle the the air-con and waited a minute before plugging it on again.

> otherwise I can help with MQTT setting message to force X50A
That would be nice :)

**Comment by revk** [comment]
OK let's try and get this sorted. My tests here did not have any problem.

A simple start is sending `setting/Faikin/protocol 7` to force X50A (inverted tx/rx). Maybe `4` if not sure if all inverted.

**Comment by jamofer** [comment]
![imagen](https://github.com/revk/ESP32-Faikin/assets/9080627/e653c4c2-effa-4ede-b7ff-2928bf8fc478)

**Comment by revk** [comment]
OK, can you bear with me a bit while I work out a way to sort a "fixed" protocol option. Hopefully not long.

**Comment by revk** [comment]
Ok that is Rx inverted and Tx not. Protocol 6 I believe...

So upgrade and send `setting/Faikin {"protocol":6,"protofix":true}`

`protofix` is a new setting to force the protocol not to change.

May then need a/c reboot but should then only try the specified protocol. If that fails, try any of 4, 5, 6, 7...

(why is it still in the panel, not snapped out? That was a really tiny board!)

**Comment by revk** [comment]
P.S. Sorry for inconvenience, I tried it on three X50 based modules here with no problem, so a tad odd.

**Comment by revk** [comment]
I may be going AFK for now, but let me know any issues.

**Comment by jamofer** [comment]
After some testing with your last build:

I tried different all X50A protocols but no one worked until I set protocol 4 and then power cycle the whole AC unit.

Now is it working! Maybe the auto-discovery protocol is messing up the AC?

These logs are after upgrading to the new version and setting up `protocol 4`:
```
setting/ac411 {"protocol":4,"protofix":true}
Faikin/ac411 {"protocol":"X50A¬Rx","ts":"2023-12-03T17:36:01Z","online":false}
state/ac411 {"ts":"2023-12-03T17:36:01Z","id":"0C8B9596F4C0","up":23,"mqtt-up":17,"restart":4,"reason":"Settings changed"}
state/ac411 {"ts":"2023-12-03T17:36:02Z","id":"0C8B9596F4C0","up":24,"mqtt-up":18,"restart":3,"reason":"Settings changed"}
error/ac411/comms {"protocol":"X50A¬Rx","badsum":"B4","data":"7EF17F753F12"}
state/ac411 {"ts":"2023-12-03T17:36:03Z","id":"0C8B9596F4C0","up":25,"mqtt-up":19,"restart":2,"reason":"Settings changed"}
state/ac411 {"ts":"2023-12-03T17:36:04Z","id":"0C8B9596F4C0","up":26,"mqtt-up":20,"restart":1,"reason":"Settings changed"}
error/ac411/comms {"protocol":"X50A¬Rx","badsum":"B4","data":"7EF17F753F12"}
state/ac411 {"ts":"2023-12-03T17:36:05Z","id":"0C8B9596F4C0","up":false,"mqtt-up":21,"reason":"Settings changed"}
state/ac411 {"ts":"2023-12-03T17:36:06Z","id":"0C8B9596F4C0","up":false,"mqtt-up":22,"reason":"Settings changed"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
state/ac411/status {"protocol":"X50A","online":false,"autor":0.0,"autot":23.5,"auto0":"00:00","auto1":"00:00","autop":false}
state/ac411 {"ts":"2023-12-03T17:36:11Z","id":"0C8B9596F4C0","up":4,"mqtt-up":1,"app":"Faikin","version":"1c7c86b","build-suffix":"-S1-PICO","build":"2023-12-03T17:29:17","flash":8388608,"rst":3,"mem":58272,"spi":2091280,"ssid":"Genuine OFDM device","bssid":"04421A178E79","rssi":-39,"chan":8,"ipv4":"192.168.1.69"}
Faikin/ac411 {"protocol":"X50A","ts":"2023-12-03T17:36:11Z","online":false}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
error/ac411/comms {"protocol":"X50A","fault":true,"data":"06FF07011502DB"}
```

**Comment by revk** [comment]
Wow, OK, `FF` there is a fault indication, but if after that it is working, then good. Wow. So, fixed?

**Comment by jamofer** [comment]
Yes! Now it works perfectly! But I think the bug is still present if I don't force the protocol. I can do more testing and give all the logs you require.

> And sorry this happened, as I say, lots of testing first.

You're doing an amazing job! it's the first bug I got after 6 months. Daikin WiFi official module stops working after few hours and there's not real support at all.

**Comment by revk** [comment]
If fixing the protocol works, I am inclined to close this, and see if any other issues pop up. I know it works here with automatic detection. Adding the option to fix it is a good enhancement just in case. Thank you for your feedback and testing.

**Comment by revk** [comment]
Actually, I have an idea, we see "error" on that from the Daikin at a lower level - try next protocol, but if the message is clean and good checksum that suggests it should accept it. So I'll change that and issue now.

**Comment by jamofer** [comment]
> Actually, I have an idea, we see "error" on that from the Daikin at a lower level - try next protocol, but if the message is clean and good checksum that suggests it should accept it. So I'll change that and issue now.
> 
> Not 100% sure if that is best as it could mean incorrect tx polarity shows error and never moves on. Hmmm.

If you need feedback I can test it this afternoon leaving the auto-discovery protocol ON again.

**Comment by revk** [comment]
Now it is right it will start from that, but you could set protocol to 0 as well and see if it finds it.

I'll have to try on my units too.

My concern is the error reply may be spot on for correct rx but wrong tx. So auto discovery may need to be a tad smarter.

**Comment by revk** [comment]
Thanks, that is excellent news.
