### ISSUE TITLE
[FEATURE] Support for more BLE temperature sensors

### ISSUE THREAD

**Issue by mike-yowen** [revk/ESP32-Daikin#237]
**Is your feature request related to a problem? Please describe.**
The support for BLE temperature sensors is great, but the ones I already have (that are picked up fine as passive BLE temperature sensors by my Shelly devices) don't seem to be supported. I am specifically looking for support for the [GoveeLife H5105](https://us.govee.com/products/goveelife-smart-thermo-hygrometer-2s) .

**Describe the solution you'd like**
Add support for GoveeLife BLE temperature (and humidity) sensors in passive mode to the Faikin (and allow for passing the temperature and humidity values through to Home Assistant). It looks like there is already a solution in place that hopefully means you wouldn't have to start from zero - https://github.com/wcbonner/GoveeBTTempLogger. Happy to help gather any data as well.

**Comment by revk** [comment]
That code looks like it has the details needed to decode them, for several models...

- GVH5075_xxxx
- Govee_H5074_xxxx
- Govee_H5179
- GVH5177_xxxx GVH5174_xxxx GVH5100_xxxx
- GVH5183
- GVH5182

Any idea which yours is?

**Comment by revk** [comment]
Is this the same one?

[GoveeLife-Thermometer-Hygrometer-Temperature-Greenhouse](https://www.amazon.co.uk/dp/B0CDX6SNJ3/)

**Comment by revk** [comment]
Ok ordering one, so I can have a play. Anything I need to do to set it up?

**Comment by Sonic-Amiga** [comment]
Hello! Since we're talking about this...
ESP8266 doesn't have a built-in BLE. How about supporting some sort of MQTT messages maybe ? So that i could use any other device in my smart home as a reference. For example, room sensor on my thermostats, driving electric heated floors. They are already intergrated with my smart home (yes, those are from Danfoss and i reverse engineered them); My smarthome controller could act as a gateway, supplying the temperature value.

**Comment by revk** [comment]
We do support a control message with env and target. My environmental sensors use this over MQTT. This has been there a lot longer than the BLE stuff.

**Comment by revk** [comment]
The eagle has landed - I'll probably look tomorrow.
![IMG_4616](https://github.com/revk/ESP32-Faikin/assets/996983/b5b1b17c-46ca-4d86-b4b5-4e9310e98d4a)

**Comment by revk** [comment]
In latest beta, do test. GVH5105 found and reported...

**Comment by revk** [comment]
Can you check settings, and turn on BLE? It should not have lost that, but worth checking.

**Comment by revk** [comment]
Code has a check for showing that based on a `remote` state, which is set based on MQTT `control` messages. Any reason you would have these? If you do, they set the temperature, not BLE, hence hiding the option.

The other is the `nofaikinauto` setting, if that is set, again, no auto mode is shown, including BLE settings.

**Comment by revk** [comment]
You found the issue?
