### ISSUE TITLE
Add support for brp069b42

### ISSUE THREAD

**Issue by WheresWes** [revk/ESP32-Daikin#4]
If I were to purchase one of these daikin modules (required for the FTXZ-N units) and assist (under guidance!) in recording its comms to the heat pump, would it be possible to add support for them?

**Comment by revk** [comment]
If you can dump the protocol with details of the actions I can have a look for you.

**Comment by timon37** [comment]
Really sorry for asking regarding a closed issue, but I don't see FTXZ in the "working list" and looking through the code I couldn't find any mention of this.
Just want to confirm that FTXZ units are currently "not expected to work"?
By the way, thanks for your work!
