### ISSUE TITLE
Randomly turns itself on

### ISSUE THREAD

**Issue by JeanOlivier** [revk/ESP32-Daikin#42]
Seemingly randomly, the AC with the Faikin turns itself on.
This could lead to non-negligible power waste.

Please tell me how I can debug this. I have MQTT configured with Home Assistant, but know basically nothing about it.
In Home Assistant, there's a log at 2:50:00 AM this morning that only says "changed to Cool". 
The same thing appened one previous evening at a similarly "round" number, but I don't remember exactly.

My unit is a north american CTXS09HVJU.

**Comment by revk** [comment]
It is only supposed to do that if the automatic controls are set. Can you confirm what settings you have done?

I can obviously check to confirm this is not happening otherwise.

**Comment by revk** [comment]
I just looked at the code, there is an "Auto" setting that has to be switched on to allow it to automatically turn on or off.

Or the time settings for auto on/off would need to be set.

if you have any means to log MQTT messages covering when this happens, that would provide a lot more details. Messages starting `info/` and the device name.

**Comment by JeanOlivier** [comment]
I did mess with them at some point, but I think I disabled them afterwards.

Here's the current local control page:
![Screenshot_20230606-093758-590](https://github.com/revk/ESP32-Faikin/assets/11236668/52e6ace8-99c7-4b4f-84af-655b3291402a)

Maybe there's an issue here, with the Auto being green even though it says "Off"? Pressing it doesn't change anything.
Note that it's set turn on at 7:50 it it's on, and it turned on at 2:50 this morning, which is 7:50 UK time. Maybe it's a time zone thing?

**Comment by JeanOlivier** [comment]
> I just looked at the code, there is an "Auto" setting that has to be switched on to allow it to automatically turn on or off.
> 
> Or the time settings for auto on/off would need to be set.
> 
> if you have any means to log MQTT messages covering when this happens, that would provide a lot more details. Messages starting `info/` and the device name.

How do I send/log commands with MQTT? Pointers welcome.
Otherwise, how can I turn off the automated local controls? I can't set the times to "None", only an actual time, and I can't seem to make the "Auto" button not green.

**Comment by JeanOlivier** [comment]
I'm in Canada, the timezone is Eastern Daylight Time (EDT) which is GMT-4.

**Comment by revk** [comment]
Ok this site has a list of time zone strings, you need to send MQTT like `setting/nameofac/tz GMT+0BST,M3.5.0,M10.5.0` but with the setting for where you are from the list.

https://gist.github.com/alwynallan/24d96091655391107939

`00:00` is a valid time, your phone must be a tad weird, but `00:00` is `12:00 AM`. It should have been that when you started. Setting that for on and off would disable. However, I am also making it so setting both the same also disables.

Update to latest code, and go to Settings and it will show the current local time, so you can see.

**Comment by revk** [comment]
As you have an issue with MQTT, I am just working on adding timeline to the "settings" page. Bear with me.

**Comment by JeanOlivier** [comment]
Could the "Auto" button on the right of that line also control if the unit will turn on or off?
Otherwise, what does it do exactly?

I'll test the timezone setting and update later today when I'm home, it's a little tedious to do remotely.

Thank you for your quick support!

**Comment by revk** [comment]
The unit turns on and off on time if the times are set.

The separate Auto times on/off based on temperature, if it is way outside target and off, or stable within target for a long time and on.

I'll look at the manual and add more detail.

**Comment by revk** [comment]
I should have timezone setting in "settings" soon, bear with me.

**Comment by JeanOlivier** [comment]
I just updated and I see that it was indeed using the BST timezone. I'll try to set it to the proper one tonight. I also set both times to 12:00AM so we'll see if that fixes all of my issues.

If it might add a request, a On/Off toggle for the auto on/off times would be great, as one could turn it off without changing the times, but turn it on again easily. E.g. when there's a few cold days during the summer or a hot period in winter.

A last question, do the automated local controls with a target temp and buffer also work without the BLE device? Does it uses the internal temp then?

Thank you again for the quick support.

**Comment by revk** [comment]
Yes, well, in theory, the automated local controls can work without the BLE. Basically give it a try.

I'll look at the time being turned on/off. It gets to be a feature creep. People will want day of week as well, and so on. So not sure best approach yet.

**Comment by revk** [comment]
There are tool tips, honest, but I'll see what I can do.

Right now, simply adding timezone setting is actually causing me to go down a rabbit hole of something else not working.
